<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-633JMIIJ" ignored="0" name="test1" tests="4" failures="2" timestamp="2020-11-11T10:50:20 CST" time="5.66" errors="0">
  <testcase name="demo1" time="0.007" classname="com.webtest.demo.demo">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at com.webtest.demo.demo.demo1(demo.java:11)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- demo1 -->
  <testcase name="demo2" time="0.001" classname="com.webtest.demo.demo"/>
  <testcase name="demo3" time="0.0" classname="com.webtest.demo.demo">
    <failure type="java.lang.AssertionError" message="expected [2] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [3]
at com.webtest.demo.demo.demo3(demo.java:19)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- demo3 -->
  <testcase name="demo4" time="0.0" classname="com.webtest.demo.demo"/>
</testsuite> <!-- test1 -->
